apiVersion: v1
kind: Pod
metadata:
 name: test-hostpath
spec:
 containers:
  -image: nginx
  name: nginx
  volumneMounts:
   -monuntPath: data
   name: datavolume
  volumes:
   -name: datavolume
   hostPath:
    path: datademo  